# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-25 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_auto_20190625_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
    ]
