# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-25 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_auto_20190625_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='reader',
        ),
        migrations.AddField(
            model_name='quote',
            name='fav',
            field=models.ManyToManyField(related_name='favs', to='quote.User'),
        ),
    ]
