# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-25 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_auto_20190625_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.CharField(max_length=255),
        ),
    ]
